
params:
  VALIDATION_DATASIZE : 5000
  EPOCHS : 3
  BATCH_SIZE : 32
  NUM_CLASSES : 10
  LOSS_FUNCTION : sparse_categorical_crossentropy
  OPTIMIZER : SGD
  METRICS : ['accuracy']
  patience : 5
  restore_best_weights : True

 

artifacts:
  ARTIFACTS_DIR: artifacts
  MODEL_DIR : model
  PLOTS_DIR : plots
  CHECKPOINTS_DIR : checkpoints

  MODEL_NAME : model.keras
  plots_name : accuracy-lossCurve

logs:
  LOGS_DIR : logs
  GENERAL_LOGS_DIR : general_logs
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_logs 